#! /bin/bash -p
### BEGIN INIT INFO
# Provides: wildfly
# Required-Start: network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Bring up/down wildfly
# Description: Bring up/down wildfly
### END INIT INFO
# Source function library.
. /etc/init.d/functions
wildfly=/home/jbosspi/wildfly-8.0.0.Final/bin/start_pi.sh
prog=wildfly
export LAUNCH_JBOSS_IN_BACKGROUND="true"
export JBOSS_PIDFILE=/home/jbosspi/wildfly-8.0.0.Final/bin/jboss.pid

start() {
    echo -n "Starting $prog:"
    $wildfly > /home/jbosspi/server.log&
    retval=$?
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    if [ -f "$JBOSS_PIDFILE" ]; then
       pid=`cat "$JBOSS_PIDFILE"`
       shell_pid=$(ps -ef | awk '$2 ~ /\<'$pid'\>/ { print $3; }')
       echo "kill pid: $shell_pid"
       kill $shell_pid
       if [ "$?" -eq 0 ]; then
         sleep 10
         kill -9 $shell_pid &> /dev/null
       fi
       kill -9 $pid &> /dev/null
    else
       warn "No pid found!"
    fi
    echo "exiting stop method"
    success
}

restart() {
    stop
    start
}

status() {
	if [ -f $JBOSS_PIDFILE ]; then
		read ppid < $JBOSS_PIDFILE
		if [ `ps --pid $ppid 2> /dev/null | grep -c $ppid 2> /dev/null` -eq '1' ]; then
			echo "$prog is running (pid $ppid)"
			return 0
		else
			echo "$prog dead but pid file exists"
			return 1
		fi
	fi
	echo "$prog is not running"
	return 3
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		status
		;;
	*)
		## If no parameters are given, print which are avaiable.
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
		;;
esac
